export const flashCards = [
{
    topic: "HTML",
    bullet1: "is a programming language",
    bullet2: "creates structure",
    bullet3: "base of every website",
    questionAsked: "What is HTML?",
    questionImg: "helo",
    answer1: "A programming language",
    answer2: "A new way of cooking",
    answer3: "A new video game",
    answer4: "An old way to write",
    solutionAnswer: "HTML is a programming language",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "A programming language",
},

{
    topic: "JavaScript",
    bullet1: "is a programming language",
    bullet2: "creates logic",
    bullet3: "uses camelCase",
    questionAsked: "What is the naming convention of JavaScript?",
    questionImg: "helo",
    answer1: "Be very poetic",
    answer2: "Use a lot of numbers",
    answer3: "Use CamelCase",
    answer4: "No-one cares",
    solutionAnswer: "JavaScript uses camelCases",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "Use CamelCase",
},

{
    topic: "CSS",
    bullet1: "is a programming language",
    bullet2: "defines the looks",
    bullet3: "always looks messy",
    questionAsked: "How does CSS code looks like?",
    questionImg: "helo",
    answer1: "Mine is pink, what about you?",
    answer2: "It always looks messy",
    answer3: "Clean, sorted and readable",
    answer4: "Like spagetthi!",
    solutionAnswer: "CSS code always looks messy",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "It always looks messy",
},

{
    topic: "The modern API",
    bullet1:'Is treated more like a product then code',
    bullet2: 'Software intermediary that allows two applications to talk to each other',
    bullet3:'Allows the user to complete the action without leaving your website',
    questionAsked: 'How is an API treated now a days?',
    questionImg: "-",
    answer1: "Like my grand-ma - with a lot of cake!",
    answer2: "As pure native code",
    answer3: "More like a product then code",
    answer4: "As systematic implementation",
    solutionAnswer: "API's are generally treated more as a product then as code.",
    explenation1: "This is due to the popularity by the users and thus large demand from companies.",
    explenation2: "",
    correctAnswer: "More like a product then code",
},

{
    topic: "Queries",
    bullet1: "A request for information from a database",
    bullet2: "There are several so called query languages",
    bullet3: "Queries are actions performed in the backend",
    questionAsked: "What are query languages?",
    questionImg: "-",
    answer1: "SQL",
    answer2: "An ancient tongue",
    answer3: "Several of them exist",
    answer4: "Datalog, HTML, JS are all query languages",
    solutionAnswer: "There are several so called query languages existing.",
    explenation1: "SQL and Datalog are indeed some of them.",
    explenation2: "",
    correctAnswer: "Several of them exist",
},

]