export const flashCards = [
{
    topic: "HTML",
    bullet1: "Stands for Hypertext Markup Language",
    bullet2: "Creates structure",
    bullet3: "Base of every website",
    questionAsked: "What does HTML stands for?",
    questionImg: "helo",
    answer1: "Hypertext Markup Language",
    answer2: "A new way of cooking",
    answer3: "A new video game",
    answer4: "An old way to write",
    solutionAnswer: "HTML stands for Hypertext Markup Language",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "Hypertext Markup Language",
},

{
    topic: "JavaScript",
    bullet1: "Is a programming language",
    bullet2: "Creates logic",
    bullet3: "Uses camelCase",
    questionAsked: "What is the naming convention of JavaScript?",
    questionImg: "helo",
    answer1: "Be very poetic",
    answer2: "Use a lot of numbers",
    answer3: "Use CamelCase",
    answer4: "No-one cares",
    solutionAnswer: "JavaScript uses camelCases",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "Use CamelCase",
},

{
    topic: "React",
    bullet1: "An open-source JavaScript library",
    bullet2: "Can change data, without reloading the page",
    bullet3: "Uses JSX",
    questionAsked: "What programming language is React?",
    questionImg: "helo",
    answer1: "Language of library",
    answer2: "JSX",
    answer3: "Not a programming language",
    answer4: "French?",
    solutionAnswer: "React is not a programming language",
    explenation1: "It is a so called library.",
    explenation2: "In React we use JSX.",
    correctAnswer: "Not a programming language",
},

{
    topic: "The modern API",
    bullet1:'Is treated more like a product then code',
    bullet2: 'Software intermediary that allows two applications to talk to each other',
    bullet3:'Allows the user to complete the action without leaving your website',
    questionAsked: 'How is an API treated now a days?',
    questionImg: "-",
    answer1: "Like my grand-ma - with a lot of cake!",
    answer2: "As pure native code",
    answer3: "More like a product then code",
    answer4: "As systematic implementation",
    solutionAnswer: "API's are generally treated more as a product then as code.",
    explenation1: "This is due to the popularity by the users and thus large demand from companies.",
    explenation2: "",
    correctAnswer: "More like a product then code",
},

{
    topic: "Queries",
    bullet1: "A request for information from a database",
    bullet2: "There are several so called query languages",
    bullet3: "Queries are actions performed in the backend",
    questionAsked: "What are query languages?",
    questionImg: "-",
    answer1: "SQL",
    answer2: "An ancient tongue",
    answer3: "Several of them exist",
    answer4: "Datalog, HTML, JS are all query languages",
    solutionAnswer: "There are several so called query languages existing.",
    explenation1: "SQL and Datalog are indeed some of them.",
    explenation2: "",
    correctAnswer: "Several of them exist",
},

]