export const flashCards = [
{
    topic: "HTML",
    bullet1: "is a programming language",
    bullet2: "creates structure",
    bullet3: "base of every website",
    questionAsked: "What is HTML?",
    questionImg: "helo",
    answer1: "a programming language",
    answer2: "a new way of cooking",
    answer3: "a new video game",
    answer4: "an old way to write",
    solutionAnswer: "HTML is a programming language",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "a programming language",
},

{
    topic: "JavaScript",
    bullet1: "is a programming language",
    bullet2: "creates logic",
    bullet3: "uses camelCase",
    questionAsked: "What is the naming convention of JavaScript?",
    questionImg: "helo",
    answer1: "be very poetic",
    answer2: "use a lot of numbers",
    answer3: "use CamelCase",
    answer4: "no-one cares",
    solutionAnswer: "JavaScript uses camelCases",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "use CamelCase",
},

{
    topic: "CSS",
    bullet1: "is a programming language",
    bullet2: "defines the looks",
    bullet3: "always looks messy",
    questionAsked: "How does CSS code looks like?",
    questionImg: "helo",
    answer1: "mine is pink, what about you?",
    answer2: "it always looks messy",
    answer3: "clean, sorted and readable",
    answer4: "like spagetthi!",
    solutionAnswer: "CSS code always looks messy",
    explenation1: "-",
    explenation2: "-",
    correctAnswer: "it always looks messy",
}
]